apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: s3-bucket-example
spec:
  crossplane:
    version: ">=v1.8"
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.28.1"
