---
apiVersion: crossplane.jonashackt.io/v1alpha1
kind: StorageAzure
metadata:
  namespace: default
  name: managed-storageaccount
spec:
  compositionRef:
    name: storageazure-composition
  parameters:
    location: West Europe
