apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: objectstorage-composition
spec:
  compositeTypeRef:
    # The XR's apiVersion must match this version here:
    apiVersion: crossplane.jonashackt.io/v1
    kind: ObjectStorage 
  mode: Pipeline
  pipeline:
  - step: create-bucket-and-public-access-objects
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: bucket
        base:
          apiVersion: s3.aws.m.upbound.io/v1beta1
          kind: Bucket
          metadata: {}
          spec:
            #deletionPolicy: Delete
        
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.bucketName"
            toFieldPath: "metadata.name"
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.region"
            toFieldPath: "spec.forProvider.region"

      - name: bucketpublicaccessblock
        base:
          apiVersion: s3.aws.m.upbound.io/v1beta1
          kind: BucketPublicAccessBlock
          spec:
            forProvider:
              blockPublicAcls: false
              blockPublicPolicy: false
              ignorePublicAcls: false
              restrictPublicBuckets: false

        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.bucketName"
            toFieldPath: "metadata.name"
            transforms:
              - type: string
                string:
                  type: Format
                  fmt: "%s-pab"
          - type: PatchSet
            patchSetName: bucketNameAndRegionPatchSet

      - name: bucketownershipcontrols
        base:
          apiVersion: s3.aws.m.upbound.io/v1beta1
          kind: BucketOwnershipControls
          spec:
            forProvider:
              rule:
                objectOwnership: ObjectWriter

        patches:
          - type: FromCompositeFieldPath  
            fromFieldPath: "spec.parameters.bucketName"
            toFieldPath: "metadata.name"
            transforms:
              - type: string
                string:
                  type: Format
                  fmt: "%s-osc"
          - type: PatchSet
            patchSetName: bucketNameAndRegionPatchSet

      - name: bucketacl
        base:
          apiVersion: s3.aws.m.upbound.io/v1beta1
          kind: BucketACL
          spec:
            forProvider:
              acl: "public-read"

        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.bucketName"
            toFieldPath: "metadata.name"
            transforms:
              - type: string
                string:
                  type: Format
                  fmt: "%s-acl"
          - type: PatchSet
            patchSetName: bucketNameAndRegionPatchSet
    
      - name: bucketwebsiteconfiguration
        base:
          apiVersion: s3.aws.m.upbound.io/v1beta1
          kind: BucketWebsiteConfiguration
          spec:
            forProvider:
              indexDocument:
                suffix: index.html

        patches:
          - type: FromCompositeFieldPath  
            fromFieldPath: "spec.parameters.bucketName"
            toFieldPath: "metadata.name"
            transforms:
              - type: string
                string:
                  type: Format
                  fmt: "%s-websiteconf"
          - type: PatchSet
            patchSetName: bucketNameAndRegionPatchSet

      patchSets:
      - name: bucketNameAndRegionPatchSet
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.bucketName"
          toFieldPath: "spec.forProvider.bucketRef.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"
