apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storageazure-composition
spec:
  compositeTypeRef:
    apiVersion: crossplane.jonashackt.io/v1
    kind: StorageAzure
  
  mode: Pipeline
  pipeline:
  - step: create-bucket-and-public-access-objects
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: storageaccount
        base:
          apiVersion: storage.azure.m.upbound.io/v1beta1
          kind: Account
          metadata: {}
          spec:
            forProvider:
              accountKind: StorageV2
              accountTier: Standard
              accountReplicationType: LRS
        patches:
          - fromFieldPath: spec.parameters.storageAccountName
            toFieldPath: metadata.name
          - fromFieldPath: spec.parameters.resourceGroupName
            toFieldPath: spec.forProvider.resourceGroupName
          - fromFieldPath: spec.parameters.location
            toFieldPath: spec.forProvider.location
            
      - name: resourcegroup
        base:
          apiVersion: azure.m.upbound.io/v1beta1
          kind: ResourceGroup
          metadata: {}
        patches:
          - fromFieldPath: spec.parameters.resourceGroupName
            toFieldPath: metadata.name
          - fromFieldPath: spec.parameters.location
            toFieldPath: spec.forProvider.location