apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: storagesazure.crossplane.jonashackt.io
spec:
  scope: Namespaced
  group: crossplane.jonashackt.io
  names:
    kind: StorageAzure
    plural: storagesazure

  versions:
  # This version should only change, when the parameters defined also change - and thus create a new version
  - name: v1
    served: true
    referenceable: true
    # See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  location:
                    type: string
                  resourceGroupName:
                    type: string
                  storageAccountName:
                    type: string
                required:
                  - location
                  - resourceGroupName
                  - storageAccountName